<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ClmCharacter;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineORMClmCharacterRepository extends \Doctrine\ORM\EntityRepository implements ClmCharacterRepositoryInterface
{
    /**
     * @param ClmCharacter $clmCharacter
     */
    public function save(ClmCharacter $clmCharacter)
    {
        $this->getEntityManager()->persist($clmCharacter);
        $this->getEntityManager()->flush();
    }

    /**
     * @param $name
     * @return ClmCharacter[]
     */
    public function findByName($name)
    {
        return $this->findBy([
            'name' => $name,
        ]);
    }
}
