<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ClmCharacter;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;

/**\
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineORMClmCharacterRepository extends \Doctrine\ORM\EntityRepository implements ClmCharacterRepositoryInterface
{
    /**
     * @param ClmCharacter $clmCharacter
     * @throws UniqueConstraintViolationException
     */
    public function save(ClmCharacter $clmCharacter)
    {
        $em = $this->getEntityManager();
        $em->persist($clmCharacter);
        try {
            $em->flush();
        } catch (UniqueConstraintViolationException $ex) {
            throw $ex;
        }
    }
    /**
     * @param $name
     * @return ClmCharacter[]
     */
    public function findByName($name)
    {
        return $this->findBy([
            'name' => $name,
        ]);
    }
}
