<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ClmItem;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineORMClmItemRepository extends \Doctrine\ORM\EntityRepository implements ClmItemRepositoryInterface
{
    /**
     * @param ClmItem $clmItem
     */
    public function save(ClmItem $clmItem)
    {
        $this->getEntityManager()->persist($clmItem);
        $this->getEntityManager()->flush();
    }

    /**
     *
     * @param $name
     * @return ClmItem[]
     */
    public function findByName($name)
    {
        return $this->findBy([
            'name' => $name,
        ]);
    }
}
