# app/config/config_eadmin.yml
easy_admin:
    entities:
        Accounts:
            class: AppBundle\Entity\ClmAccount
        Characters:
            class: AppBundle\Entity\ClmCharacter
        Users:
            class: AppBundle\Entity\User
            form:
                fields: ['username', 'email', 'enabled', 'roles', 'lastLogin']
            list:
                fields: ['username', 'email', 'enabled', 'roles', 'lastLogin']
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete' }
    design:
        menu:
            - { entity: 'Users', icon: 'user'}
            - { entity: 'Accounts', icon: 'user'}
            - { entity: 'Characters', icon: 'user'}
