fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_list:
  path: /user/list
  defaults:
    _controller: app.controller.user:listAction

user_import:
  path: /user/import
  defaults:
    _controller: app.controller.user:importAction

user_show:
  path: /user/show/{id}
  defaults:
    _controller: app.controller.user:showAction
    id: 1

raid_show:
  path: /raid/show/{id}
  defaults:
    _controller: app.controller.raid:showAction
    id: 1

redirect_home:
  path: /{slug}
  defaults:
    _controller: FrameworkBundle:Redirect:Redirect
    route: user_list
  requirements:
    slug: .*
