redirect_home:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:Redirect
    route: user_list
    permanent: true

user_list:
  path: /users/list
  defaults:
    _controller: app.controller.user:listAction

user_import:
  path: /users/import
  defaults:
    _controller: app.controller.user:importAction