redirect_home:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:Redirect
    route: user_list
    permanent: true

user_list:
  path: /user/list
  defaults:
    _controller: app.controller.user:listAction

user_import:
  path: /user/import
  defaults:
    _controller: app.controller.user:importAction

user_show:
  path: /user/show/{id}
  defaults:
    _controller: app.controller.user:showAction
    id: 1