# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.repository.account:
      class: AppBundle\Repository\ClmAccountRepositoryInterface
      factory: ['@doctrine', 'getRepository']
      arguments: ['AppBundle:ClmAccount']

  app.repository.raid:
      class: AppBundle\Repository\ClmRaidRepositoryInterface
      factory: ['@doctrine', 'getRepository']
      arguments: ['AppBundle:ClmRaid']

  app.repository.character:
      class: AppBundle\Repository\ClmCharacterRepositoryInterface
      factory: ['@doctrine', 'getRepository']
      arguments: ['AppBundle:ClmCharacter']

  app.service.user_manager:
      class: AppBundle\Service\UserLootManager
      arguments:
        - '@app.repository.account'
        - '@app.repository.raid'

  app.controller.user:
      class: AppBundle\Controller\UserController
      arguments:
        - '@templating'
        - '@router'
        - '@form.factory'
        - '@app.service.user_manager'
        - '@app.xml_deserializer'

  app.controller.raid:
      class: AppBundle\Controller\RaidController
      arguments:
        - '@templating'
        - '@router'
        - '@form.factory'
        - '@app.service.user_manager'

  app.xml_deserializer:
      class: AppBundle\Service\ClmXmlDeserializer
      arguments:
          - '@app.repository.account'
          - '@app.repository.character'

  app.menu_builder:
      class: AppBundle\Menu\MenuBuilder
      arguments: ['@knp_menu.factory', '@security.authorization_checker']
      tags:
          - { name: knp_menu.menu_builder, method: createNavMenu, alias: nav }
          - { name: knp_menu.menu_builder, method: createSideMenu, alias: side_nav }
          - { name: knp_menu.menu_builder, method: createUserMenu, alias: user_nav}
          - { name: knp_menu.menu_builder, method: createRaidDropButton, alias: raid_drop_button}
          - { name: knp_menu.menu_builder, method: createRaidDropContent, alias: raid_drop_content}
