# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  hautelook_alice.bare_faker:
      class: Faker\Generator
      factory: [ Faker\Factory, create ]
      lazy: true
      arguments:
          - %hautelook_alice.locale%
      calls:
          - [ seed, [ %hautelook_alice.seed% ] ]

  faker.provider.conanitemprovider:
      class: AppBundle\DataFixtures\Faker\Provider\ConanItemProvider
      arguments: [ "@hautelook_alice.bare_faker" ]
      tags: [ { name: "hautelook_alice.faker.provider" } ]

  app.repository.user:
      class: AppBundle\Repository\UserRepositoryInterface
      factory: ['@doctrine', 'getRepository']
      arguments: ['AppBundle:User']

  app.service.user_manager:
      class: AppBundle\Service\UserLootManager
      arguments: ['@app.repository.user']

  app.user_controller:
      class: AppBundle\Controller\UserController
      arguments: ['@templating', '@app.service.user_manager']
