# src\AppBundle\Resources\config\serializer\Entity.ClmAccount.yml
AppBundle\Entity\ClmAccount:
    xml_root_name: account
    exclude: true
    exclusion_policy: NONE
    properties:
        id:
            exclude: true
            expose: false
        accountName:
            expose: true
            type: string
            serialized_name: account_name
            xml_attribute: true
            xml_value: false
        tear:
            expose: true
            type: integer
            serialized_name: tear
            xml_attribute: true
            xml_value: false
        weapon:
            expose: true
            type: integer
            serialized_name: weapon
            xml_attribute: true
            xml_value: false
        acc:
            expose: true
            type: integer
            serialized_name: accessoire
            xml_attribute: true
            xml_value: false
        item:
            expose: true
            type: integer
            serialized_name: item
            xml_attribute: true
            xml_value: false
        urn:
            expose: true
            type: integer
            serialized_name: relic
            xml_attribute: true
            xml_value: false
        items:
            expose: false
            type: string
            serialized_name: name
            xml_attribute: true
            xml_value: false
            read_only: false
        characters:
            expose: false
            type: string
            serialized_name: name
            xml_attribute: true
            xml_value: false
