# src\AppBundle\Resources\config\serializer\Entity.ClmAccount.yml
AppBundle\Entity\ClmAccount:
    exclusion_policy: NONE
    expose: true
    xml_root_name: accounts
    read_only: false
    properties:
        id:
            exclude: true
            expose: false
        accountName:
            expose: true
            type: string
            serialized_name: player_name
            xml_attribute: true
            xml_value: false
        tear:
            expose: true
            type: integer
            serialized_name: tear
            xml_attribute: true
            xml_value: false
        weapon:
            expose: true
            type: integer
            serialized_name: weapon
            xml_attribute: true
            xml_value: false
        acc:
            expose: true
            type: integer
            serialized_name: accessoire
            xml_attribute: true
            xml_value: false
        item:
            expose: true
            type: integer
            serialized_name: item
            xml_attribute: true
            xml_value: false
        urn:
            expose: true
            type: integer
            serialized_name: relic
            xml_attribute: true
            xml_value: false
        items:
            expose: true
            type: string
            serialized_name: items
            xml_list: true
            read_only: false
        characters:
            expose: false
            type: string
            serialized_name: characters
            xml_list: true
            read_only: true
